name: GitHub Packages Release
on:
  push:
    branches:
      - 2023.x
      - 2025.0.x
      - 2025.1.x
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Dependencies Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: install dependencies
        run: mvn clean install -U package -pl '!spring-cloud-alibaba-coverage'  -DskipTests
      - name: cat ~/.m2/settings.xml
        run: |
          cat ~/.m2/settings.xml
      - name: Deploy to GitHub Package Maven
        run: |
          mvn clean -B deploy -pl . -DskipTests
          cd $GITHUB_WORKSPACE/spring-cloud-alibaba-dependencies
          mvn clean -B deploy -DskipTests
          cd $GITHUB_WORKSPACE/spring-cloud-alibaba-starters
          mvn clean -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}
